name: larobe.pl
favicon: null
layout_spectrum: 1
typography_spectrum: 0.5093290479853749
title: La Robe Olga Pollak-Olcha
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#89898b'
    - '#10121f'
    - '#cacbc3'
    - '#8b4e3d'
    - '#fffffd'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.9375
  rhythmicContrast: 1
purpose: []
