name: larobe.pl
favicon: null
layout_spectrum: 0.01445
typography_spectrum: 0.5093290479853749
title: La Robe Olga Pollak-Olcha
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#141517'
    - '#56534e'
    - '#878c90'
    - '#d9d8d4'
  brandStrength: 1
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
