name: larobe.pl
favicon: null
layout_spectrum: 0.15461017354391515
typography_spectrum: 0.5093290479853749
title: La Robe Olga Pollak-Olcha
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.13838717062026262
  lightness: 0.16682950733229518
  saturation: 0.8809451281558722
  rhythmicContrast: 0.3160090632736683
purpose: []
